name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop, collin/github_actions]
  pull_request:
    branches: [ master, develop ]

# NOTE Much of what I do with run commands directly has other github action specific ways I just didnt care and did it with commands
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gen-docs:
    runs-on: ubuntu-latest
    env:
      DOCKER_NAME: docsbuild
    steps:
      - name: setup-env
        run: |
          cd $GITHUB_WORKSPACE
      - name: checkout
        uses: actions/checkout@v2
      - name: docker-build
        run: |
          docker build -t $DOCKER_NAME:latest ./
      - name: document
        run: |
          docker run --name $DOCKER_NAME "make docs"
      - name: copy
        run: |
          rm -rf docs/ &&
          docker cp $DOCKER_NAME:/home/developer/robocup-firmware/docs .
      - name: push
        run: |
          cd docs/ &&
          git add --all -f &&
          git commit -m 'auto-updated documentation' &&
          git push https://$GH_TOKEN@github.com/robojackets/robocup-firmware gh-pages
